#!/usr/bin/env bash
set -Eeuo pipefail
umask 077

ROOT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)
cd "$ROOT_DIR"
RESUME=0
if [[ ${1:-} == --resume && $# == 1 ]]; then
  RESUME=1
elif (( $# != 0 )); then
  printf '用法：%s [--resume]\n' "$0" >&2
  exit 2
fi

fail() {
  printf '安装失败：%s\n' "$*" >&2
  exit 1
}

for tool in docker mktemp openssl; do
  command -v "$tool" >/dev/null 2>&1 || fail "缺少 $tool"
done
docker compose version >/dev/null 2>&1 || fail '需要 Docker Compose v2'
docker info >/dev/null 2>&1 || fail '无法连接 Docker，请检查服务和当前用户权限'
[[ -f compose.yaml ]] || fail '找不到 compose.yaml'

# Keep the project name stable even if the checkout is moved later.
PROJECT=quota-watch
if (( RESUME == 1 )); then
  [[ -f .env ]] || fail '没有 .env，首次安装请直接运行 ./install.sh'
  grep -Fxq '# Generated by quota-watch install.sh' .env || fail '现有 .env 不是本脚本生成的，不能用 --resume；请按 UPDATING.md 核对'
  grep -Fxq "COMPOSE_PROJECT_NAME=$PROJECT" .env || fail '现有 .env 的 Compose 项目名已改变，请手动核对'
  username=$(sed -n 's/^QUOTA_WATCH_USERNAME=//p' .env)
  password=$(sed -n 's/^QUOTA_WATCH_PASSWORD=//p' .env)
  master_key=$(sed -n 's/^QUOTA_WATCH_MASTER_KEY=//p' .env)
  [[ $username =~ ^qw_[0-9a-f]{16}$ && $password =~ ^[A-Za-z0-9+/]{32}$ && $master_key =~ ^[A-Za-z0-9+/]{43}=$ ]] \
    || fail '现有 .env 凭据不完整，请手动核对'
  chmod 600 .env
  existing_containers=$(docker ps -aq --filter 'label=com.docker.compose.service=quota-watch') || fail '无法检查现有容器'
  while IFS= read -r candidate; do
    [[ -n $candidate ]] || continue
    deployed_dir=$(docker inspect --format '{{index .Config.Labels "com.docker.compose.project.working_dir"}}' "$candidate")
    deployed_project=$(docker inspect --format '{{index .Config.Labels "com.docker.compose.project"}}' "$candidate")
    [[ -d $deployed_dir && $deployed_project == "$PROJECT" ]] || fail '现有容器不属于本次安装，不能继续'
    [[ $(cd "$deployed_dir" && pwd -P) == "$ROOT_DIR" ]] || fail '现有容器来自其他目录，不能继续'
  done <<< "$existing_containers"
else
  [[ ! -e .env ]] || fail '已有 .env；为避免更换现有凭据，请使用 ./update.sh；首次安装失败可运行 ./install.sh --resume'
  existing_containers=$(docker ps -aq --filter 'label=com.docker.compose.service=quota-watch') || fail '无法检查现有容器'
  if [[ -n $existing_containers ]]; then
    fail '已存在 quota-watch 容器；请在原部署目录使用 ./update.sh'
  fi
  existing_volumes=$(docker volume ls -q --filter 'label=com.docker.compose.volume=quota-watch-data') || fail '无法检查现有数据卷'
  if [[ -n $existing_volumes ]] || \
    docker volume inspect "${PROJECT}_quota-watch-data" >/dev/null 2>&1; then
    fail '已存在 quota-watch 数据卷；请先确认原部署和数据，不能生成新密钥覆盖旧配置'
  fi

  username="qw_$(openssl rand -hex 8)"
  password=$(openssl rand -base64 24 | tr -d '\r\n')
  master_key=$(openssl rand -base64 32 | tr -d '\r\n')
  [[ -n $username && -n $password && -n $master_key ]] || fail '随机凭据生成失败'

  # Write completely before publishing; hard-linking cannot replace an
  # existing .env if another installer races with this one.
  temp_env=$(mktemp "$ROOT_DIR/.env.tmp.XXXXXX") || fail '无法创建临时凭据文件'
  trap 'rm -f -- "$temp_env"' EXIT
  printf '# Generated by quota-watch install.sh\nCOMPOSE_PROJECT_NAME=%s\nQUOTA_WATCH_USERNAME=%s\nQUOTA_WATCH_PASSWORD=%s\nQUOTA_WATCH_MASTER_KEY=%s\nTZ=Asia/Shanghai\n' \
    "$PROJECT" "$username" "$password" "$master_key" > "$temp_env" || fail '无法写入临时凭据文件'
  chmod 600 "$temp_env"
  ln "$temp_env" .env || fail '无法创建 .env；已有文件时不会覆盖'
  rm -f -- "$temp_env"
  trap - EXIT
fi

compose() (
  unset QUOTA_WATCH_USERNAME QUOTA_WATCH_PASSWORD QUOTA_WATCH_MASTER_KEY \
    QUOTA_WATCH_DATA_DIR QUOTA_WATCH_LISTEN COMPOSE_PROJECT_NAME TZ
  docker compose --project-directory "$ROOT_DIR" --env-file "$ROOT_DIR/.env" \
    -p "$PROJECT" -f "$ROOT_DIR/compose.yaml" "$@"
)

compose config --quiet || fail 'Compose 配置检查失败；已生成的凭据保存在 .env'
compose up -d --build quota-watch || fail 'Docker 构建或启动失败；凭据保存在 .env，排查后可运行 ./install.sh --resume'

container=$(compose ps -q quota-watch)
[[ -n $container ]] || fail '找不到新容器；凭据仍保存在 .env'
for ((attempt = 0; attempt < 90; attempt++)); do
  health=$(docker inspect --format '{{if .State.Health}}{{.State.Health.Status}}{{else}}{{.State.Status}}{{end}}' "$container" 2>/dev/null || true)
  if [[ $health == healthy ]]; then
    printf '\nQuota Watch 已安装并通过健康检查。\n'
    printf '访问地址：http://127.0.0.1:8091\n'
    printf '登录账号：%s\n' "$username"
    printf '登录密码：%s\n' "$password"
    printf '凭据与主密钥保存在 %s/.env，请妥善备份。\n' "$ROOT_DIR"
    printf '如需从远程电脑访问，请使用 SSH 隧道；Sub2API 地址与管理员 Key 在登录后配置。\n'
    exit 0
  fi
  sleep 2
done
fail '容器未在 3 分钟内通过健康检查；凭据仍保存在 .env，排查日志后可运行 ./install.sh --resume'
